-- Create the jishotech database
CREATE DATABASE IF NOT EXISTS jishotech;
USE jishotech;

-- Create Topics table
CREATE TABLE topics (
    id_topic INT PRIMARY KEY AUTO_INCREMENT,
    topic_name VARCHAR(255) NOT NULL
);

-- Create Words table
CREATE TABLE words (
    id_word INT PRIMARY KEY AUTO_INCREMENT,
    kanji VARCHAR(255),
    katakana VARCHAR(255),
    romaji VARCHAR(255),
    hiragana VARCHAR(255) NOT NULL,
    meaning VARCHAR(255) NOT NULL,
    example VARCHAR(255),       
    status VARCHAR(255),
    link VARCHAR(255)
);

-- Create WordTopic table
CREATE TABLE wordtopic (
    id_wordtopic INT PRIMARY KEY AUTO_INCREMENT,
    id_topic INT NOT NULL,
    id_word INT NOT NULL,
    FOREIGN KEY (id_topic) REFERENCES topics(id_topic),
    FOREIGN KEY (id_word) REFERENCES words(id_word)
);

-- Create User table
CREATE TABLE users (
    id_user INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,    
    password VARCHAR(255) NOT NULL,
    phone_number INT,
    status INT NOT NULL
);

-- Create Bookmark table
CREATE TABLE bookmarks (
    id_bookmark INT PRIMARY KEY AUTO_INCREMENT,
    id_word INT NOT NULL,
    id_user INT NOT NULL,
    FOREIGN KEY (id_word) REFERENCES words(id_word),
    FOREIGN KEY (id_user) REFERENCES users(id_user)
);

-- Create Quizz table
CREATE TABLE quizzes (
    id_quizz INT PRIMARY KEY AUTO_INCREMENT,
    id_topic INT NOT NULL,
    id_user INT NOT NULL,
    question VARCHAR(255) NOT NULL,
    right_answer VARCHAR(255) NOT NULL,
    FOREIGN KEY (id_topic) REFERENCES topics(id_topic),
    FOREIGN KEY (id_user) REFERENCES users(id_user)
);
 
-- Insert words into words table
INSERT INTO `jishotech`.`words` (`id_word`, `kanji`, `katakana`, `romaji`, `hiragana`, `meaning`, `example`, `status`, `link`) VALUES 
 (1, '登録', NULL, NULL, 'とうろく', 'Đăng ký', NULL, NULL, NULL),
 (2, '連絡先', NULL, NULL, 'れんらくさき', 'Thông tin liên lạc', NULL, NULL, NULL),
 (3, '大事', NULL, NULL, 'だいじ', 'Quan trọng', NULL, NULL, NULL),
 (4, '情報資産', NULL, NULL, 'じょうほうしさん', 'Tài sản thông tin', NULL, NULL, NULL),
 (5, '無くす', NULL, NULL, 'なくす', 'Làm mất', NULL, NULL, NULL),
 (6, '盗む', NULL, NULL, 'ぬすむ', 'Ăn cắp', NULL, NULL, NULL),
 (7, '悪用', NULL, NULL, 'あくよう', 'Lạm dụng', NULL, NULL, NULL),
 (8, '対策', NULL, NULL, 'たいさく', 'Biện pháp đối phó', NULL, NULL, NULL),
 (9, '守る', NULL, NULL, 'まもる', 'Giữ', NULL, NULL, NULL),
 (10, '機密性', NULL, NULL, 'きみつせい', 'Tính bảo mật', NULL, NULL, NULL),
 (11, '完全性', NULL, NULL, 'かんぜんせい', 'Tính toàn vẹn', NULL, NULL, NULL),
 (12, '可用性', NULL, NULL, 'かようせい', 'Tính khả dụng', NULL, NULL, NULL),
 (13, '維持する', NULL, NULL, 'いじする', 'Duy trì', NULL, NULL, NULL),
 (14, '不正', NULL, NULL, 'ふせい', 'Bất hợp pháp', NULL, NULL, NULL),
 (15, '第三者', NULL, NULL, 'だいさんしゃ', 'Người thứ ba/bên thứ ba', NULL, NULL, NULL),
 (16, '情報漏えい', NULL, NULL, 'じょうほうろうえい', 'Rò rỉ thông tin', NULL, NULL, NULL),
 (17, '暗号化', NULL, NULL, 'あんごうか', 'Mã hoá', NULL, NULL, NULL),
 (18, '向上', NULL, NULL, 'こうじょう', 'Tăng cường, nâng cao', NULL, NULL, NULL),
 (19, '書き換える', NULL, NULL, 'かきかえる', 'Viết lại', NULL, NULL, NULL),
 (20, '欠ける', NULL, NULL, 'かける', 'Khuyết, thiếu', NULL, NULL, NULL),
 (21, 'ディジタル署名', NULL, NULL, 'ディジタルしょめい/\nデジタルしょめい', 'Chữ ký điện tử', NULL, NULL, NULL),
 (22, '定期', NULL, NULL, 'ていき', 'Định kỳ', NULL, NULL, NULL),
 (23, '電子透かし', NULL, NULL, 'でんしすかし', 'Thuỷ vân số (Digital watermarking)', NULL, NULL, NULL),
 (24, '画像', NULL, NULL, 'がぞう', 'Hình ảnh', NULL, NULL, NULL),
 (25, '音声', NULL, NULL, 'おんせい', 'Âm thanh', NULL, NULL, NULL),
 (26, '動画', NULL, NULL, 'どうが', 'Video', NULL, NULL, NULL),
 (27, '埋め込む', NULL, NULL, 'うめこむ', 'Nhúng', NULL, NULL, NULL),
 (28, '作者名', NULL, NULL, 'さくしゃめい', 'Tên tác giả', NULL, NULL, NULL),
 (29, '課金情報', NULL, NULL, 'かきんじょうほう', 'Thông tin thanh toán', NULL, NULL, NULL),
 (30, 'コピー可能回数', NULL, NULL, 'コピーかのうかいすう', 'Số lần sao chép khả dụng', NULL, NULL, NULL),
 (31, '不正コピー', NULL, NULL, 'ふせいコピー', 'Sao chép bất hợp pháp', NULL, NULL, NULL),
 (32, 'データ改ざん', NULL, NULL, 'データかいざん', 'Giả mạo/Xuyên tạc dữ liệu', NULL, NULL, NULL),
 (33, '判別する', NULL, NULL, 'はんべつする', 'Phân biệt', NULL, NULL, NULL),
 (34, '装う', NULL, NULL, 'よそおう', 'Giả vờ, ngụy trang', NULL, NULL, NULL),
 (35, '侵入する', NULL, NULL, 'しんにゅうする', 'Xâm nhập', NULL, NULL, NULL),
 (36, '外部流出', NULL, NULL, 'がいぶりゅうしゅつ', 'Rò rỉ ra ngoài', NULL, NULL, NULL),
 (37, '自己増殖', NULL, NULL, 'じこぞうしょく', 'Tự sinh sôi', NULL, NULL, NULL),
 (38, '単独', NULL, NULL, 'たんどく', 'Một mình', NULL, NULL, NULL),
 (39, '経由', NULL, NULL, 'けいゆ', 'Thông qua', NULL, NULL, NULL),
 (40, '入り込む', NULL, NULL, 'いりこむ', 'Đi vào', NULL, NULL, NULL),
 (41, '脅威', NULL, NULL, 'きょうい', 'Mối đe dọa', NULL, NULL, NULL),
 (42, '晒す', NULL, NULL, 'さらす', 'Phơi bày, lộ ra', NULL, NULL, NULL),
 (43, 'きちんと把握する', NULL, NULL, 'きちんとはあくする', 'Nắm bắt một cách rõ ràng', NULL, NULL, NULL),
 (44, '技術的脅威', NULL, NULL, 'ぎじゅつてききょうい', 'Mối đe dọa kỹ thuật', NULL, NULL, NULL),
 (45, '人的脅威', NULL, NULL, 'じんてききょうい', 'Mối đe dọa con người', NULL, NULL, NULL),
 (46, '物理的脅威', NULL, NULL, 'ぶつりてききょうい', 'Mối đe dọa vật lý', NULL, NULL, NULL),
 (47, '手口', NULL, NULL, 'てぐち', 'Thủ thuật', NULL, NULL, NULL),
 (48, '攻撃', NULL, NULL, 'こうげき', 'Tấn công', NULL, NULL, NULL),
 (49, '装う', NULL, NULL, 'よそおう', 'Giả/ngụy trang', NULL, NULL, NULL),
 (50, '偽', NULL, NULL, 'にせ', 'Giả', NULL, NULL, NULL),
 (51, '載せる', NULL, NULL, 'のせる', 'Đặt, đăng', NULL, NULL, NULL),
 (52, '電子メール', NULL, NULL, 'でんしメール', 'Thư điện tử', NULL, NULL, NULL),
 (53, 'URLを載せた電子メール', NULL, NULL, 'ユーアールエルをのせたでんしメール', 'Thư điện tử có chứa đường dẫn đến trang web', NULL, NULL, NULL),
 (54, '暗証番号', NULL, NULL, 'あんしょうばんごう', 'Mã số bảo mật', NULL, NULL, NULL),
 (55, 'だまし取る', NULL, NULL, 'だましとる', 'Lừa gạt để lấy đi...', NULL, NULL, NULL),
 (56, '参照する', NULL, NULL, 'さんしょうする', 'Tham khảo, tham chiếu', NULL, NULL, NULL),
 (57, '誤る', NULL, NULL, 'あやまる', 'Bị lỗi, sai', NULL, NULL, NULL),
 (58, '覚え込む', NULL, NULL, 'おぼえこむ', 'Nhớ', NULL, NULL, NULL),
 (59, '誘導する', NULL, NULL, 'ゆうどうする', 'Xúi giục/dẫn dắt làm điều xấu', NULL, NULL, NULL),
 (60, '悪意', NULL, NULL, 'あくい', 'Ác ý, độc hại', NULL, NULL, NULL),
 (61, '問合せる', NULL, NULL, 'といあわせる', 'Truy vấn', NULL, NULL, NULL),
 (62, '操作', NULL, NULL, 'そうさ', 'Thao tác', NULL, NULL, NULL),
 (63, '命令文', NULL, NULL, 'めいれいぶん', 'Câu lệnh', NULL, NULL, NULL),
 (64, '取得する', NULL, NULL, 'しゅとくする', 'Đạt được, có được', NULL, NULL, NULL),
 (65, '防ぐ', NULL, NULL, 'ふせぐ', 'Đề phòng, dự phòng', NULL, NULL, NULL),
 (66, '入力中', NULL, NULL, 'にゅうりょくちゅう', 'Trong quá trình nhập vào', NULL, NULL, NULL),
 (67, '解釈', NULL, NULL, 'かいしゃく', 'Giải nghĩa, cắt nghĩa', NULL, NULL, NULL),
 (68, '無効化', NULL, NULL, 'むこうか', 'Vô hiệu hoá', NULL, NULL, NULL),
 (69, '大量', NULL, NULL, 'たいりょう', 'Số lượng lớn', NULL, NULL, NULL),
 (70, '機能', NULL, NULL, 'きのう', 'Chức năng', NULL, NULL, NULL),
 (71, '停止する', NULL, NULL, 'ていしする', 'Dừng', NULL, NULL, NULL),
 (72, '管理者', NULL, NULL, 'かんりしゃ', 'Người quản lý', NULL, NULL, NULL),
 (73, '意図', NULL, NULL, 'いと', 'Ý định, chủ ý', NULL, NULL, NULL),
 (74, '指定', NULL, NULL, 'してい', 'Chỉ định', NULL, NULL, NULL),
 (75, '許可', NULL, NULL, 'きょか', 'Cho phép', NULL, NULL, NULL),
 (76, '閲覧', NULL, NULL, 'えつらん', 'Duyệt', NULL, NULL, NULL),
 (77, '動向', NULL, NULL, 'どうこう', 'Xu hướng', NULL, NULL, NULL),
 (78, '収集', NULL, NULL, 'しゅうしゅう', 'Thu thập', NULL, NULL, NULL),
 (79, '監視', NULL, NULL, 'かんし', 'Giám sát', NULL, NULL, NULL),
 (80, '記録', NULL, NULL, 'きろく', 'Ghi lại', NULL, NULL, NULL),
 (81, 'こっそり', NULL, NULL, NULL, 'Vụng trộm, lén lút', NULL, NULL, NULL),
 (82, '仕掛ける', NULL, NULL, 'しかける', 'Thiết lập', NULL, NULL, NULL),
 (83, 'SQL文', NULL, NULL, 'エスキューエルぶん', 'Câu lệnh SQL', NULL, NULL, NULL),
 (84, '置き忘れ', NULL, NULL, 'おきわすれ', 'Để quên', NULL, NULL, NULL),
 (85, '操作ミス', NULL, NULL, 'そうさミス', 'Lỗi thao tác', NULL, NULL, NULL),
 (86, 'もち主', NULL, NULL, 'もちぬし', 'Người chủ sở hữu', NULL, NULL, NULL),
 (87, 'うっかりミス', NULL, NULL, NULL, 'Lỗi vô ý', NULL, NULL, NULL),
 (88, '内部関係者', NULL, NULL, 'ないぶかんけいしゃ', 'Người trong cuộc', NULL, NULL, NULL),
 (89, '聞き出す', NULL, NULL, 'ききだす', 'Hỏi', NULL, NULL, NULL),
 (90, '緊急事態', NULL, NULL, 'きんきゅうじたい', 'Trường hợp khẩn cấp', NULL, NULL, NULL),
 (91, '組織内部', NULL, NULL, 'そしきないぶ', 'Nội bộ tổ chức', NULL, NULL, NULL),
 (92, '機密情報', NULL, NULL, 'きみつじょうほう', 'Thông tin cơ mật', NULL, NULL, NULL),
 (93, '人間の心理', NULL, NULL, 'にんげんのしんり', 'Tâm lý con người', NULL, NULL, NULL),
 (94, '隙を付く', NULL, NULL, 'すきをつく', 'Lợi dụng lỗ hổng', NULL, NULL, NULL),
 (95, '盗む行為', NULL, NULL, 'ぬすむこうい', 'Hành vi ăn cắp', NULL, NULL, NULL),
 (96, 'なりすまし', NULL, NULL, NULL, 'Mạo danh', NULL, NULL, NULL),
 (97, '人のふり', NULL, NULL, 'ひとのふり', 'Giả vờ là người đó', NULL, NULL, NULL),
 (98, '他人', NULL, NULL, 'たにん', 'Người khác', NULL, NULL, NULL),
 (99, '迷惑', NULL, NULL, 'めいわく', 'Làm phiền', NULL, NULL, NULL),
 (100, '行動', NULL, NULL, 'こうどう', 'Hành động', NULL, NULL, NULL),
 (101, 'サラミ法', NULL, NULL, 'サラミほう', 'Phương pháp salami (Salami slicing)\n(サラミテクニック：Salami technique)', NULL, NULL, NULL),
 (102, '不正行為', NULL, NULL, 'ふせいこうい', 'Hành vi bất hợp pháp/Gian lận', NULL, NULL, NULL),
 (103, '表面化', NULL, NULL, 'ひょうめんか', 'Bề mặt hoá', NULL, NULL, NULL),
 (104, '程度', NULL, NULL, 'ていど', 'Mức độ', NULL, NULL, NULL),
 (105, '多数の資産', NULL, NULL, 'たすうのしさん', 'Nhiều tài sản', NULL, NULL, NULL),
 (106, '詐取', NULL, NULL, 'さしゅ', 'Gian lận, lừa gạt', NULL, NULL, NULL),
 (107, '大雨', NULL, NULL, 'おおあめ', 'Mưa lớn', NULL, NULL, NULL),
 (108, '地震', NULL, NULL, 'じしん', 'Động đất', NULL, NULL, NULL),
 (109, '落雷', NULL, NULL, 'らくらい', 'Sấm sét', NULL, NULL, NULL),
 (110, '災害', NULL, NULL, 'さいがい', 'Thảm họa', NULL, NULL, NULL),
 (111, '故障', NULL, NULL, 'こしょう', 'Hỏng hóc', NULL, NULL, NULL),
 (112, '損害', NULL, NULL, 'そんがい', 'Hư hại', NULL, NULL, NULL),
 (113, '失う', NULL, NULL, 'うしなう', 'Mất, đánh mất', NULL, NULL, NULL),
 (114, '空き巣', NULL, NULL, 'あきす', 'Kẻ trộm', NULL, NULL, NULL),
 (115, '盗難', NULL, NULL, 'とうなん', 'Trộm cắp', NULL, NULL, NULL),
 (116, '破壊', NULL, NULL, 'はかい', 'Phá huỷ', NULL, NULL, NULL),
 (117, 'リスクを洗い出す', NULL, NULL, 'リスクをあらいだす', 'Xác định rủi ro', NULL, NULL, NULL),
 (118, 'リスク対応', NULL, NULL, 'リスクたいおう', 'Ứng phó rủi ro', NULL, NULL, NULL),
 (119, 'リスク回避', NULL, NULL, 'リスクかいひ', 'Tránh rủi ro', NULL, NULL, NULL),
 (120, 'リスク移転', NULL, NULL, 'リスクいてん', 'Chuyển rủi ro', NULL, NULL, NULL),
 (121, 'リスク共有', NULL, NULL, 'リスクきょうゆう', 'Chia sẻ rủi ro', NULL, NULL, NULL),
 (122, 'リスク軽減', NULL, NULL, 'リスクけいげん', 'Giảm thiểu rủi ro', NULL, NULL, NULL),
 (123, 'リスク保有', NULL, NULL, 'リスクほゆう', 'Chấp nhận rủi ro', NULL, NULL, NULL),
 (124, '予測リスク', NULL, NULL, 'よそくリスク', 'Rủi ro dự đoán trước', NULL, NULL, NULL),
 (125, '明らか', NULL, NULL, 'あきらか', 'Rõ ràng', NULL, NULL, NULL),
 (126, '策定する', NULL, NULL, 'さくていする', 'Xây dựng', NULL, NULL, NULL),
 (127, '一連', NULL, NULL, 'いちれん', 'Một chuỗi', NULL, NULL, NULL),
 (128, '分析', NULL, NULL, 'ぶんせき', 'Phân tích', NULL, NULL, NULL),
 (129, '得る', NULL, NULL, 'える', 'Đạt được', NULL, NULL, NULL),
 (130, '損失額', NULL, NULL, 'そんしつがく', 'Tỉ lệ tổn thất', NULL, NULL, NULL),
 (131, '発生確率', NULL, NULL, 'はっせいかくりつ', 'Xác suất phát sinh', NULL, NULL, NULL),
 (132, '発生時', NULL, NULL, 'はっせいじ', 'Thời điểm phát sinh', NULL, NULL, NULL),
 (133, '被害', NULL, NULL, 'ひがい', 'Thiệt hại', NULL, NULL, NULL),
 (134, '評価する', NULL, NULL, 'ひょうかする', 'Đánh giá', NULL, NULL, NULL),
 (135, '優先度', NULL, NULL, 'ゆうせんど', 'Độ ưu tiên', NULL, NULL, NULL),
 (136, '優先度をつける', NULL, NULL, 'ゆうせんどをつける', 'Ưu tiên', NULL, NULL, NULL),
 (137, '検討する', NULL, NULL, 'けんとうする', 'Xem xét', NULL, NULL, NULL),
 (138, '排除する', NULL, NULL, 'はいじょする', 'Loại trừ', NULL, NULL, NULL),
 (139, '発生率', NULL, NULL, 'はっせいりつ', 'Tỉ lệ phát sinh', NULL, NULL, NULL),
 (140, '破棄', NULL, NULL, 'はき', 'Bỏ đi', '彼女は一方的に婚約を破棄した\n見られたくないテストはこっそり破棄する', NULL, NULL),
 (141, '公開', NULL, NULL, 'こうかい', 'Công khai', NULL, NULL, NULL),
 (142, '他者', NULL, NULL, 'たしゃ', 'Người khác', NULL, NULL, NULL),
 (143, '肩代わする', NULL, NULL, 'かたがわする', 'Chịu trách nhiệm', NULL, NULL, NULL),
 (144, '保険', NULL, NULL, 'ほけん', 'Bảo hiểm', NULL, NULL, NULL),
 (145, '加入', NULL, NULL, 'かにゅう', 'Gia nhập', NULL, NULL, NULL),
 (146, '許容範囲内', NULL, NULL, 'きょようはんいない', 'Trong phạm vi chịu đựng được', NULL, NULL, NULL),
 (147, '対策を講じない', NULL, NULL, 'たいさくをこうじない', 'Không thực hiện các biện pháp đối phó', NULL, NULL, NULL),
 (148, '応じる', NULL, NULL, 'おうじる', 'Trả lời', NULL, NULL, NULL),
 (149, '優先順位付け', NULL, NULL, 'ゆうせんじゅんいづけ', 'Sắp xếp thứ tự ưu tiên', NULL, NULL, NULL),
 (150, '優先順位を付ける', NULL, NULL, 'ゆうせんじゅんいをつける', 'Sắp xếp thứ tự ưu tiên', NULL, NULL, NULL),
 (151, '種別', NULL, NULL, 'しゅべつ', 'Kiểu', NULL, NULL, NULL),
 (152, '事例', NULL, NULL, 'じれい', 'Nghiên cứu điển hình', NULL, NULL, NULL),
 (153, '企業', NULL, NULL, 'きぎょう', 'Xí nghiệp', NULL, NULL, NULL),
 (154, '適切', NULL, NULL, 'てきせつ', 'Thích hợp', NULL, NULL, NULL),
 (155, '確立する', NULL, NULL, 'かくりつする', 'Thành lập', NULL, NULL, NULL),
 (156, '継続的', NULL, NULL, 'けいぞくてき', 'Tiếp diễn', NULL, NULL, NULL),
 (157, '改善', NULL, NULL, 'かいぜん', 'Cải tiến', NULL, NULL, NULL),
 (158, '手順', NULL, NULL, 'てじゅん', 'Quy trình', NULL, NULL, NULL),
 (159, 'おおよそ', NULL, NULL, NULL, 'Đại khái', NULL, NULL, NULL),
 (160, '適用宣言書', NULL, NULL, 'てきようせんげんしょ', 'Bản tuyên bố áp dụng\n（Statement Of Applicability）', NULL, NULL, NULL),
 (161, '大まか', NULL, NULL, 'おおまか', 'Khái quát/chung chung', NULL, NULL, NULL),
 (162, '取り扱う', NULL, NULL, 'とりあつかう', 'Xử lý', NULL, NULL, NULL),
 (163, 'ノート型PC', NULL, NULL, 'ノートがたピーシー', 'Máy tính xách tay', NULL, NULL, NULL),
 (164, '持ち歩く', NULL, NULL, 'もちあるく', 'Mang đi, mang theo', NULL, NULL, NULL),
 (165, '紛失', NULL, NULL, 'ふんしつ', 'Tổn thất', NULL, NULL, NULL),
 (166, '磁気ディスク', NULL, NULL, 'じきディスク', 'Đĩa từ', NULL, NULL, NULL),
 (167, '廃棄する', NULL, NULL, 'はいきする', 'Thải/bỏ, tiêu hủy', '私たちは仕方なく在庫を廃棄した', NULL, NULL),
 (168, '産業廃棄物処理業者', NULL, NULL, 'さんぎょうはいきぶつしょりぎょうしゃ', 'Công ty xử lý rác thải công nghiệp', NULL, NULL, NULL),
 (169, '引き渡す', NULL, NULL, 'ひきわたす', 'Trao/giao', NULL, NULL, NULL),
 (170, '全領域', NULL, NULL, 'ぜんりょういき', 'Toàn bộ vùng', NULL, NULL, NULL),
 (171, '上書きする', NULL, NULL, 'うわがきする', 'Viết đè lên', NULL, NULL, NULL),
 (172, '消去', NULL, NULL, 'しょうきょ', 'Xóa', NULL, NULL, NULL),
 (173, '添付', NULL, NULL, 'てんぷ', 'Đính kèm', NULL, NULL, NULL),
 (174, '記載せず', NULL, NULL, 'きさいぜず', 'Không mô tả （≈記載しない）', NULL, NULL, NULL),
 (175, '手段', NULL, NULL, 'しゅだん', 'Phương tiện', NULL, NULL, NULL),
 (176, '宛先', NULL, NULL, 'あてさき', 'Bên nhận', NULL, NULL, NULL),
 (177, '間違える', NULL, NULL, 'まちがえる', 'Sai', NULL, NULL, NULL),
 (178, '誤送信', NULL, NULL, 'ごそうしん', 'Gửi sai/nhầm', NULL, NULL, NULL),
 (179, '訪問者', NULL, NULL, 'ほうもんしゃ', 'Khách, người đến thăm', NULL, NULL, NULL),
 (180, '市販', NULL, NULL, 'しはん', 'Có sẵn trên thị trường, được bày bán trên thị trường', NULL, NULL, NULL),
 (181, '脆弱性', NULL, NULL, 'ぜいじゃくせい', 'Lỗ hổng bảo mật', NULL, NULL, NULL),
 (182, '宿主', NULL, NULL, 'しゅくしゅ', 'Máy chủ', NULL, NULL, NULL),
 (183, '探す', NULL, NULL, 'さがす', 'Tìm kiếm', NULL, NULL, NULL),
 (184, '自己伝染', NULL, NULL, 'じこでんせん', 'Tự lây nhiễm', NULL, NULL, NULL),
 (185, '繰り返す', NULL, NULL, 'くりかえす', 'Lặp đi lặp lại', NULL, NULL, NULL),
 (186, '急増', NULL, NULL, 'きゅうぞう', 'Tăng đột ngột', NULL, NULL, NULL),
 (187, '表示', NULL, NULL, 'ひょうじ', 'Hiển thị', NULL, NULL, NULL),
 (188, '脅かす', NULL, NULL, 'おびやかす', 'Đe doạ', NULL, NULL, NULL),
 (189, '過負荷状態', NULL, NULL, 'かふかじょうたい', 'Tình trạng quá tải', NULL, NULL, NULL),
 (190, '盗聴', NULL, NULL, 'とうちょう', 'Nghe trộm', NULL, NULL, NULL),
 (191, '書き換える', NULL, NULL, 'かきかえる', 'Viết lại', NULL, NULL, NULL),
 (192, '該当する', NULL, NULL, 'がいとうする', 'Áp dụng, tương ứng', NULL, NULL, NULL),
 (193, '低下する', NULL, NULL, 'ていかする', 'Hạ xuống', NULL, NULL, NULL),
 (194, '分散する', NULL, NULL, 'ぶんさんする', 'Phân tán', NULL, NULL, NULL),
 (195, '除去する', NULL, NULL, 'じょきょする', 'Xoá', NULL, NULL, NULL),
 (196, '扱う', NULL, NULL, 'あつかう', 'Xử lý', NULL, NULL, NULL),
 (197, '分解する', NULL, NULL, 'ぶんかいする', 'Chia/tách', NULL, NULL, NULL),
 (198, '集約する', NULL, NULL, 'しゅうやくする', 'Tóm tắt', NULL, NULL, NULL),
 (199, '付加する', NULL, NULL, 'ふかする', 'Thêm vào', NULL, NULL, NULL),
 (200, '媒体', NULL, NULL, 'ばいたい', 'Phương tiện truyền dẫn, vật trung gian, dung môi', NULL, NULL, NULL),
 (201, '遠隔地', NULL, NULL, 'えんかくち', 'Vùng ở xa', NULL, NULL, NULL),
 (202, '保管する', NULL, NULL, 'ほかんする', 'Bảo quản, giữ gìn', NULL, NULL, NULL);;
